- name: cart configuration
  hosts: cart
  become: yes
  tasks:
    - name: disable nodejs module
      ansible.builtin.command: dnf module disable nodejs -y

    - name: enable nodejs module 20
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: Install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present
    
    - name: Add application cart
      ansible.builtin.cart:
        name: roboshop
        home: /app
        system: true
        shell: /sbin/nologin
        comment: "roboshop system cart"
    
    #remove app directory if it exists
    - name: Recursively remove directory
      ansible.builtin.file:
       path: /app
       state: absent

    - name: Create a directory if it does not exist
      ansible.builtin.file:
       path: /app
       state: directory

    - name: delete cart zip file
      ansible.builtin.file:
        path: /tmp/cart.zip
        state: absent

    - name: Download cart code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
        dest: /tmp/cart.zip      

    - name: Extract cart.zip  into /app
      ansible.builtin.unarchive:
        src: /tmp/cart.zip
        dest: /app
        remote_src: yes

    - name: Install packages based on package.json.
      community.general.npm:
        path: /app
    - name: copy service file to /etc/systemd/system/cart.service
      ansible.builtin.template:
        src: cart.service
        dest: /etc/systemd/system/cart.service
      
    - name: Reload systemd
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: start cart
      ansible.builtin.service:
        name: cart
        state: restarted
        enabled: yes