- name: catalogue configuration
  hosts: catalogue
  become: yes
  tasks:
    - name: disable nodejs module
      ansible.builtin.command: dnf module disable nodejs

    - name: enable nodejs module 20
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: Install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present
    
    - name: Add application User
      ansible.builtin.user:
        name: roboshop
        home: /app
        system: true
        shell: /sbin/nologin
        comment: "roboshop system user"
    
    #remove app directory if it exists
    - name: Recursively remove directory
      ansible.builtin.file:
       path: /app
       state: absent

    - name: Create a directory if it does not exist
      ansible.builtin.file:
       path: /app
       state: directory

    - name: delete catalogue zip file
      ansible.builtin.file:
        path: /tmp/catalogue.zip
        state: absent

    - name: Download catalogue code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
        dest: /tmp/catalogue.zip      

    - name: Extract catalogue.zip  into /app
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes

    - name: Install packages based on package.json.
      community.general.npm:
        path: /app
    - name: copy service file to /etc/systemd/system/catalogue.service
      ansible.builtin.template:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service
      notify: Reload systemd

    - name: Reload systemd
      ansible.builtin.systemd_service:
        daemon_reload: true

      #Repo copy
    - name: copying mongodb repo
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

  # Installing mongodb server 
    - name: Installing mongodb server 
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: present

  # checking data already loaded or not 
    - name: check products loaded
      ansible.builtin.command: mongosh --host "{{ MONGODB }}" --quiet  --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
      register: catalogue_output

    - name: print the output
      ansible.builtin.debug:
        msg: "{{ catalogue_output }}"

    - name: load the products
      ansible.builtin.shell: mongosh --host "{{ MONGODB }}" </app/db/master-data.js
      when: catalogue_output.stdout  | int < 0

    - name: start catalogue
      ansible.builtin.service:
        name: catalogue
        state: restarted
        enabled: yes