- name: mysql installation
  hosts: mysql
  tasks:
    - name: Installing mysql server
      ansible.builtin.dnf:
        name: mysql-server
        state: present

# service start and enable
    - name: start mysql server
      ansible.builtin.service:
        name: mysqld
        state: restarted
        enabled: yes 

    - name: Update user password
      ansible.builtin.user:
        name: root
        password: RoboShop@1
        update_password: always