- name: shipping configuration
  hosts: shipping
  become: yes
  tasks:
    - name: installing maven
      ansible.builtin.dnf:
        name: maven
        state: present

    - name: Add application user
      ansible.builtin.user:
        name: roboshop
        home: /app
        system: true
        shell: /sbin/nologin
        comment: "roboshop system shipping"
    
    #remove app directory if it exists
    - name: Recursively remove directory
      ansible.builtin.file:
       path: /app
       state: absent

    - name: Create a directory if it does not exist
      ansible.builtin.file:
       path: /app
       state: directory

    - name: delete shipping zip file
      ansible.builtin.file:
        path: /tmp/shipping.zip
        state: absent

    - name: Download shipping code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
        dest: /tmp/shipping.zip      

    - name: Extract shipping.zip  into /app
      ansible.builtin.unarchive:
        src: /tmp/shipping.zip
        dest: /app
        remote_src: yes

    - name: Installing dependencies
      ansible.builtin.command: mvn clean package
      args:
        chdir: /app

    - name: install dependencies
      ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar 
      args:
        chdir: /app
    
    - name: copy shipping.service file to /etc/systemd/system/shipping.service
      ansible.builtin.template:
        src: shipping.service
        dest: /etc/systemd/system/shipping.service

    - name: Reload systemd
      ansible.builtin.systemd_service:
        daemon_reload: true        

    - name: install dependencie
      ansible.builtin.pip:
        name: "{{ item }}"
        executable: pip3.9
      loop:
      - cryptography
      - PyMySQL

    - name: Install mysql client 
      ansible.builtin.dnf:
        name: mysql 
        state: present
    
    - name: Import shipping data
      community.mysql.mysql_db:
        state: import
        name: all
        login_host: "{{ MYSQL_HOST }}"
        login_user: root
        login_password: RoboShop@1
        target: "{{ item }}"
      loop:
        - /app/db/schema.sql
        - /app/db/app-user.sql 
        - /app/db/master-data.sql

    - name: start shipping
      ansible.builtin.service:
        name: shipping
        state: restarted
        enabled: yes