- name: user configuration
  hosts: user
  become: yes
  tasks:
    - name: disable nodejs module
      ansible.builtin.command: dnf module disable nodejs -y

    - name: enable nodejs module 20
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: Install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present
    
    - name: Add application User
      ansible.builtin.user:
        name: roboshop
        home: /app
        system: true
        shell: /sbin/nologin
        comment: "roboshop system user"
    
    #remove app directory if it exists
    - name: Recursively remove directory
      ansible.builtin.file:
       path: /app
       state: absent

    - name: Create a directory if it does not exist
      ansible.builtin.file:
       path: /app
       state: directory

    - name: delete user zip file
      ansible.builtin.file:
        path: /tmp/user.zip
        state: absent

    - name: Download user code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
        dest: /tmp/user.zip      

    - name: Extract user.zip  into /app
      ansible.builtin.unarchive:
        src: /tmp/user.zip
        dest: /app
        remote_src: yes

    - name: Install packages based on package.json.
      community.general.npm:
        path: /app
    - name: copy service file to /etc/systemd/system/user.service
      ansible.builtin.template:
        src: user.service
        dest: /etc/systemd/system/user.service
      
    - name: Reload systemd
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: start user
      ansible.builtin.service:
        name: user
        state: restarted
        enabled: yes